hw1 done
zuevmaxim/hse_java2 pull request #1
Opened 2019-01-20 21:25 UTC by zuevmaxim

2019-01-21 11:10 UTC, yurii-litvinov requested changes

2019-01-21 11:10 UTC, yurii-litvinov commented on hw1/src/main/java/com/example/Elem.java
> +public class Elem {
Самому классу тоже нужен комментарий, и это даже важнее, чем комментарии к методам --- потому что единицей декомпозиции объектно-ориентированной программы является именно класс, и про каждый класс должно быть понятно, что он делает и зачем нужен.

2019-01-21 11:10 UTC, yurii-litvinov commented on hw1/src/main/java/com/example/Elem.java
> +package com.example;
Лучше что-нибудь более специфичное, например, com.example.hashtable или com.example.hw1

2019-01-21 11:10 UTC, yurii-litvinov commented on hw1/src/main/java/com/example/Elem.java
> +     * @return key
Не надо начинать комментарии с `@return`, при этом не написав общего комментария к методу. Текст за `@return` сгенерится в детальное описание метода в документации, тогда как текст перед всеми тэгами --- в общее описание, которое показывается и в описании класса. Так что общий комментарий должен быть всегда, а вот `@return` можно и не писать.

К тому же, это как раз такой метод, назначение которого очевидно из его названия, тут лучше вообще не писать комментарий, потому что место он занимает, а пользы от него нет

2019-01-21 11:10 UTC, yurii-litvinov commented on hw1/src/main/java/com/example/Elem.java
> +    public boolean eq(Elem elem) {
Каноничнее переопределить equals

2019-01-21 11:10 UTC, yurii-litvinov commented on hw1/src/main/java/com/example/HashTable.java
> +     * @param capacity
Пустые тэги лучше не писать вовсе --- либо напишите комментарий, либо удалите. Опять-таки, место занимает, пользы не приносит.

2019-01-21 11:10 UTC, yurii-litvinov commented on hw1/src/main/java/com/example/HashTable.java
> +        return baskets[getHash(key)].find(key) != null;
Если в качестве key передадут null, будет NullReferenceException, который указывает на то, что программист о чём-то не подумал. А я бы ожидал IllegalArgumentException, который указывает на то, что о чём-то не подумал пользователь

2019-01-21 11:10 UTC, yurii-litvinov commented on hw1/src/main/java/com/example/HashTable.java
> +        return null;
Я бы и value запретил быть null, потому что сейчас непонятно, как отличить отсутствие значения от наличия значения null. Ну либо надо придумать какой-то другой способ сигнализировать об отсутствии значения

2019-01-21 11:10 UTC, yurii-litvinov commented on hw1/src/main/java/com/example/Elem.java
> +public class Elem {
Было бы лучше назвать его Element. Вообще, лучше никогда не сокращать идентификаторы (кроме общепринятых сокращений, типа счётчиков цикла, или переменных с очень маленькой областью видимости). Написать код надо один раз, а разбираться в нём может потребоваться часто, много, разным людям.

2019-01-21 11:10 UTC, yurii-litvinov commented on hw1/src/main/java/com/example/HashTable.java
> +    }
Изменение размера таблицы может привести к тому, что массив, хранящий списки, станет очень большим. clear тут с этим ничего не делает, поэтому может быть неожиданная для пользователя ситуация, которая очень похожа на утечку памяти: мы положили в таблицу миллион элементов, увидели, что у нас скушалась вся оперативка, сделали clear и обещали себе никогда больше 10 элементов в таблицу не класть. А память-то всё равно расходуется так, будто в таблице миллион элементов.

2019-01-21 11:10 UTC, yurii-litvinov commented on hw1/src/main/java/com/example/List.java
> +        public Elem elem;
Их можно было бы сделать private, объемлющий класс всё равно будет иметь к ним доступ

2019-01-21 11:10 UTC, yurii-litvinov commented on hw1/src/main/java/com/example/List.java
> +    private class Node {
На самом деле, он должен быть private static class, потому что в Java довольно извращённая система вложенных классов (https://docs.oracle.com/javase/tutorial/java/javaOO/nested.html). Создавать объекты классов, в объявлении которых есть static, довольно психоделично, но делать нечего :) Впрочем, про это потом ещё будут долго рассказывать, так что это замечание на будущее, его можно не править и никаких штрафов за это нет.

2019-01-21 11:10 UTC, yurii-litvinov commented on hw1/src/main/java/com/example/List.java
> +        public Node(Node nxt, Node prv, Elem elm) {
Имена параметров --- это святое, потому что они показываются во всплывающих подсказках. Правильнее было бы ниже написать this.next = next, чем портить тут имена

2019-01-21 11:10 UTC, yurii-litvinov commented on hw1/src/main/java/com/example/List.java
> +        size = 0;
Вообще, оно и так проинициализируется, так что конструктор можно было не писать вовсе, но это может быть хорошей привычкой для C++-программиста, так что можно не править

2019-01-21 11:10 UTC, yurii-litvinov commented on hw1/src/main/java/com/example/List.java
> +        Node newNode = new Node(head, null, elem);
Не нужно писать тип дважды. Вообще, если тип переменной очевиден из правой части, правильнее писать var.

2019-01-21 11:10 UTC, yurii-litvinov commented on hw1/src/main/java/com/example/List.java
> +            a[i++] = cur.elem;
Побочных эффектов лучше избегать. Их можно не заметить при чтении программы и сильно удивляться, к тому же порядок вычисления не всегда очевиден (тут ладно, но в общем случае нет).

2019-01-21 11:10 UTC, yurii-litvinov commented on hw1/src/main/java/com/example/Main.java
> +public class Main {
Это вообще не нужно, раз юнит-тесты есть

2019-01-21 11:10 UTC, yurii-litvinov commented on hw1/src/test/java/com/example/HashTableTest.java
> +        HashTable h = new HashTable();
Имеет смысл использовать @BeforeEach для инициализации хеш-таблицы, а то копипаст

2019-01-23 19:39 UTC, yurii-litvinov approved these changes
Теперь существенных замечаний нет, так что зачтена полностью.

2019-01-23 19:39 UTC, yurii-litvinov commented on hw1/src/main/java/com/example/hashtable/HashTable.java
> +public class HashTable {
Самому классу тоже нужен содержательный комментарий. Тут бы, например, написать хотя бы, что оно строки отображает в строки

2019-01-23 19:39 UTC, yurii-litvinov commented on hw1/src/main/java/com/example/hashtable/HashTable.java
> +        }
Вообще, в Java тоже есть constructor chaining, так что тут можно было побороться с копипастом.

2019-01-23 19:39 UTC, yurii-litvinov commented on hw1/src/main/java/com/example/hashtable/List.java
> +import org.jetbrains.annotations.Nullable;
Кажется, оно не используется нигде.

2019-01-23 19:39 UTC, yurii-litvinov commented on hw1/src/test/java/com/example/hashtable/ListTest.java
> +    private List l;
Не очень хорошее имя поля

2019-01-23 20:04 UTC, zuevmaxim commented on hw1/src/main/java/com/example/hashtable/HashTable.java
> +        }
А как именно это сделать? Если оставить только строчку 
baskets = new List[capacity];
то элементы массива будут проинициализированны null, конструктор List не вызывается.

2019-01-23 22:12 UTC, merged