Hw3 my tree set
zuevmaxim/hse_java2 pull request #3
Opened 2019-02-03 22:39 UTC by zuevmaxim

2019-02-09 13:52 UTC, yurii-litvinov requested changes
Сложновато получилось. Например, большинство операций, требующих обхода дерева, можно было сделать нерекурсивными и тем немного сэкономить строки кода (возможно). Можно было более активно переиспользовать фрагменты кода (boundedFind же сделали), тем более что лямбды, я вижу, уже используете.

2019-02-09 13:52 UTC, yurii-litvinov commented on hw3/src/main/java/com/hse/java/treeSet/BSTSet.java
> +     *  integer greater then 0, if a > b
less th**a**n и greater th**a**n, иначе это как-то не по-английски

2019-02-09 13:52 UTC, yurii-litvinov commented on hw3/src/main/java/com/hse/java/treeSet/BSTSet.java
> +        return contains((E) object, getRoot());
Вообще говоря, contains должен спокойно работать и с объектами другого типа, если компаратор не против. Иначе contains бы принимала не Object, а E или его потомков.

2019-02-09 13:52 UTC, yurii-litvinov commented on hw3/src/main/java/com/hse/java/treeSet/BSTSet.java
> +    private BSTSet<E> descendingBSTSet;
Не уверен, что это реально нужно in order to update connection with it, но почему нет. Это позволяет не создавать лишний раз новые объекты

2019-02-09 13:52 UTC, yurii-litvinov commented on hw3/src/main/java/com/hse/java/treeSet/BSTSet.java
> +    private Node<E>  lastNode() {
А тут пробел лишний :)

2019-02-09 13:52 UTC, yurii-litvinov commented on hw3/src/main/java/com/hse/java/treeSet/BSTSet.java
> +     * GT (>)  greater then
Тут тоже, `than`. then --- это "то, тогда", than --- это "чем", разные слова вообще :)

2019-02-09 13:52 UTC, yurii-litvinov commented on hw3/src/main/java/com/hse/java/treeSet/BSTSet.java
> +            E next = nextNode.element;
А если nextNode уже null?

2019-02-09 13:52 UTC, yurii-litvinov commented on hw3/src/main/java/com/hse/java/treeSet/BSTSet.java
> +        return new TreeIterator(true);
Есть подозрение, что это можно было бы реализовать как descendingSet().iterator(), что сэкономило бы сложность

2019-02-09 13:52 UTC, yurii-litvinov commented on hw3/src/test/java/com/hse/java/treeSet/BSTSetTest.java
> +        BSTSet<Time> timeSetWithoutComparator = new BSTSet<>();
Я бы тут var-ом пользовался

2019-02-11 20:15 UTC, yurii-litvinov approved these changes

2019-02-11 20:15 UTC, yurii-litvinov commented on hw3/src/main/java/com/hse/java/treeSet/BSTSet.java
> +                throw new IllegalStateException("Next element is null.");
Вообще, тут должен быть NoSuchElementException, по канонам стандартной библиотеки

2019-02-11 20:15 UTC, yurii-litvinov commented on hw3/src/main/java/com/hse/java/treeSet/BSTSet.java
> +     * Made in oder to avoid updating connection with
"order", опечатка

2019-02-11 20:15 UTC, yurii-litvinov commented on hw3/src/main/java/com/hse/java/treeSet/BSTSet.java
> +        Node<E> result = new Node<>();
Тут var был бы уместнее

2019-02-11 20:15 UTC, yurii-litvinov commented on hw3/src/test/java/com/hse/java/treeSet/BSTSetTest.java
> +        BSTSet<FormatTime> formatTimeBSTSet = new BSTSet<>(timeComparator);
И тут var бы лучше смотрелся

2019-02-11 20:25 UTC, zuevmaxim commented on hw3/src/main/java/com/hse/java/treeSet/BSTSet.java
> +        Node<E> result = new Node<>();
Но требуется именно Node<E>, а не Node<Object>. Иначе придется делать каст в конце.

2019-02-23 09:09 UTC, merged